name: mine_lab
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.1
  http: ^0.13.4
  flutter_svg: ^1.0.3
  shared_preferences: ^2.0.13
  path_provider: ^2.0.9
  intl: ^0.17.0
  pin_code_fields: ^7.3.0
  webview_flutter: ^3.0.1
  url_launcher: ^6.0.20
  flutter_widget_from_html: ^0.8.5
  animated_bottom_navigation_bar: ^0.3.2
  auto_size_text: ^3.0.0
  flutter_spinkit: ^5.1.0
  google_fonts: ^3.0.1
  awesome_dialog: ^3.0.2
  file_picker: ^5.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Light.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
